name: engaged-env-config
version: 1.4.0
patches:
  openedx-lms-production-settings: |
    DCS_SESSION_COOKIE_SAMESITE = 'Lax'
    REGISTRATION_EXTRA_FIELDS = {
        'confirm_email': 'hidden',
        'level_of_education': 'hidden',
        'gender': 'hidden',
        'year_of_birth': 'hidden',
        'mailing_address': 'hidden',
        'goals': 'hidden',
        'honor_code': 'hidden',
        'terms_of_service': 'hidden',
        'city': 'hidden',
        'country': 'hidden',
    }
  openedx-cms-production-settings: |
    DCS_SESSION_COOKIE_SAMESITE = 'Lax'
  common-env-features: |
    "MILESTONES_APP": true,
    "SKIP_EMAIL_VALIDATION": true,
    "ENABLE_DISCUSSION_HOME_PANEL": true,
    "ENABLE_DISCUSSION_EMAIL_DIGEST": true,
    "ENABLE_PASSWORD_RESET_FAILURE_EMAIL": true,
    "ORGANIZATIONS_APP": true
  cms-env-features: |
    "ENABLE_OTHER_COURSE_SETTINGS": true
  lms-env-features: |
    "ENABLE_ACCOUNT_DELETION": false,
    "ENABLE_MKTG_SITE": true,
    "COURSES_ARE_BROWSABLE": false,
    "ENABLE_BULK_ENROLLMENT_VIEW": true
  cms-env: |
    "DEFAULT_SITE_THEME": "open-edx-engaged-theme",
    "TIME_ZONE": "America/Sao_Paulo"
  lms-env: |
    "DEFAULT_SITE_THEME": "open-edx-engaged-theme",
    "MKTG_URLS": {
      "ROOT": "/dashboard"
    },
    "TIME_ZONE": "America/Sao_Paulo"
