name: engaged-env-config
version: 1.0.0
patches:
  common-env-features: |
    "ALLOW_PUBLIC_ACCOUNT_CREATION": false,
    "ENABLE_API_DOCS": true,
    "ENABLE_DISCUSSION_SERVICE": true,
    "ENABLE_DISCUSSION_HOME_PANEL": true,
    "ORGANIZATIONS_APP": true
  cms-env-features: |
    "ENABLE_OTHER_COURSE_SETTINGS": true
  lms-env-features: |
    "COURSES_ARE_BROWSABLE": false,
    "ENABLE_THIRD_PARTY_AUTH": true,
    "ENABLE_ACCOUNT_DELETION": false,
    "ENABLE_BULK_ENROLLMENT_VIEW": true
  cms-env: |
    "WIKI_ENABLED": true,
    "TIME_ZONE": "America/Sao_Paulo"
  lms-env: |
    "WIKI_ENABLED": true,
    "TIME_ZONE": "America/Sao_Paulo"
