name: engaged-env-config
version: 1.0.0
patches:
  common-env-features: |
    "SKIP_EMAIL_VALIDATION": true,
    "ENABLE_API_DOCS": true,
    "ENABLE_DISCUSSION_SERVICE": true,
    "ENABLE_DISCUSSION_HOME_PANEL": true,
    "ORGANIZATIONS_APP": true
  cms-env-features: |
    "ENABLE_OTHER_COURSE_SETTINGS": true
  lms-env-features: |
    "ENABLE_MKTG_SITE": true,
    "COURSES_ARE_BROWSABLE": false,
    "ENABLE_THIRD_PARTY_AUTH": true,
    "ENABLE_BULK_ENROLLMENT_VIEW": true
  cms-env: |
    "DEFAULT_SITE_THEME": "open-edx-engaged-theme",
    "WIKI_ENABLED": true,
    "TIME_ZONE": "America/Sao_Paulo"
  lms-env: |
    "DEFAULT_SITE_THEME": "open-edx-engaged-theme",
    "MKTG_URLS": {
      "ROOT": "/dashboard"
    },
    "WIKI_ENABLED": true,
    "TIME_ZONE": "America/Sao_Paulo"
